# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7]
        exclude:
          - os: windows-latest
            python-version: 3.6
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Conda list
      shell: bash -l {0}
      run: conda list
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        conda install scikit-learn==0.23.2
        pip install featuretools==0.27.1
        pip install git+https://github.com/DataCanvasIO/Hypernets
        conda install -y -c conda-forge prophet==1.0.1
        pip install -r requirements.txt
        pip install pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hyperts --durations=30
